---
- name: 'update and upgrade packages.'
  become: yes
  apt:
    upgrade: yes
    update_cache: yes
    cache_valid_time: 86400
- name: remove unneeded deps
  become: yes
  apt:
    autoremove: yes
- name: install deps
  become: yes
  apt:
    name: ['nodejs', 'npm']
    state: latest
    update_cache: yes
- name: install pm2
  become: yes
  npm:
    name: pm2
    global: yes
    state: latest
    production: yes
- name: "Create backend directory"
  file:
    path: ~/project/backend_app_dir
    state: directory

- name: "Copy artifact into instance"
  become: yes
  copy:
    src: ~/project/artifact.tar.gz
    dest: /home/ubuntu/backend_app_dir/artifact.tar.gz

- name: start app
  become: yes
  shell: |
    cd /home/ubuntu/backend_app_dir
    tar xzvf artifact.tar.gz
    npm install
    npm run build
    pm2 delete all
    pm2 start npm -- start